# Generated by Django 4.1.7 on 2023-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название не указано', max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название не указано', max_length=256, verbose_name='Название')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('volume', models.CharField(default='Объем не указан', max_length=256, verbose_name='Объем')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен к заказу')),
                ('extras', models.ManyToManyField(to='bar.extras', verbose_name='Дополнительные ингредиенты')),
            ],
        ),
    ]
