# Generated by Django 4.1.7 on 2023-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcard',
            name='extras',
            field=models.ManyToManyField(blank=True, to='bar.extras', verbose_name='Дополнительные ингредиенты'),
        ),
    ]
